# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui',
# licensing of 'form.ui' applies.
#
# Created: Thu Aug 29 11:24:26 2019
#      by: pyside2-uic  running on PySide2 5.13.0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 492)
        Form.setStyleSheet("QWidget#Form{border-width : 1px; border-style : solid; border-color : black; border-radius : 7px}\")\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 614, 406))
        self.widget1.setObjectName("widget1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.title_label_3 = QtWidgets.QLabel(self.widget1)
        self.title_label_3.setStyleSheet("")
        self.title_label_3.setObjectName("title_label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.title_label_3)
        self.title_edit_3 = QtWidgets.QLineEdit(self.widget1)
        self.title_edit_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.title_edit_3.setObjectName("title_edit_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.title_edit_3)
        self.date_label_3 = QtWidgets.QLabel(self.widget1)
        self.date_label_3.setObjectName("date_label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.date_label_3)
        self.dateTime_edit_3 = QtWidgets.QDateTimeEdit(self.widget1)
        self.dateTime_edit_3.setMaximumSize(QtCore.QSize(105, 16777215))
        self.dateTime_edit_3.setObjectName("dateTime_edit_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateTime_edit_3)
        self.lig_label_5 = QtWidgets.QLabel(self.widget1)
        self.lig_label_5.setObjectName("lig_label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lig_label_5)
        self.lig_combo_5 = QtWidgets.QComboBox(self.widget1)
        self.lig_combo_5.setMaximumSize(QtCore.QSize(250, 16777215))
        self.lig_combo_5.setObjectName("lig_combo_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lig_combo_5)
        self.location_label_3 = QtWidgets.QLabel(self.widget1)
        self.location_label_3.setObjectName("location_label_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.location_label_3)
        self.location_combo_3 = QtWidgets.QComboBox(self.widget1)
        self.location_combo_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.location_combo_3.setObjectName("location_combo_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.location_combo_3)
        self.description_label_5 = QtWidgets.QLabel(self.widget1)
        self.description_label_5.setObjectName("description_label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.description_label_5)
        self.description_edit_5 = QtWidgets.QTextEdit(self.widget1)
        self.description_edit_5.setMaximumSize(QtCore.QSize(450, 16777215))
        self.description_edit_5.setObjectName("description_edit_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.description_edit_5)
        self.team_label_3 = QtWidgets.QLabel(self.widget1)
        self.team_label_3.setObjectName("team_label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.team_label_3)
        self.teamWidget_3 = QtWidgets.QWidget(self.widget1)
        self.teamWidget_3.setMaximumSize(QtCore.QSize(450, 16777215))
        self.teamWidget_3.setObjectName("teamWidget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.teamWidget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teamWidgetLayout = QtWidgets.QVBoxLayout()
        self.teamWidgetLayout.setObjectName("teamWidgetLayout")
        self.horizontalLayout.addLayout(self.teamWidgetLayout)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.teamWidget_3)
        self.row7_hlyaout = QtWidgets.QHBoxLayout()
        self.row7_hlyaout.setObjectName("row7_hlyaout")
        self.cancel_btn = QtWidgets.QPushButton(self.widget1)
        self.cancel_btn.setObjectName("cancel_btn")
        self.row7_hlyaout.addWidget(self.cancel_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.row7_hlyaout.addItem(spacerItem)
        self.save_btn = QtWidgets.QPushButton(self.widget1)
        self.save_btn.setObjectName("save_btn")
        self.row7_hlyaout.addWidget(self.save_btn)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.row7_hlyaout)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.title_label_3.setText(QtWidgets.QApplication.translate("Form", "Title:", None, -1))
        self.date_label_3.setText(QtWidgets.QApplication.translate("Form", "Date & Time:", None, -1))
        self.lig_label_5.setText(QtWidgets.QApplication.translate("Form", "League:", None, -1))
        self.location_label_3.setText(QtWidgets.QApplication.translate("Form", "Location:", None, -1))
        self.description_label_5.setText(QtWidgets.QApplication.translate("Form", "Description:", None, -1))
        self.team_label_3.setText(QtWidgets.QApplication.translate("Form", "Team:", None, -1))
        self.cancel_btn.setText(QtWidgets.QApplication.translate("Form", "Cancel", None, -1))
        self.save_btn.setText(QtWidgets.QApplication.translate("Form", "Save", None, -1))

